### ISSUE TITLE
Error reading <address-id>: TimeoutError: Timeout has occurred

### ISSUE THREAD

**Issue by pklopotowski** [andrei-tatar/node-red-contrib-nibetcp#1]
I created a flow to collect data from a S1155 heat pump. I only added a few nodes, but after a short period of time exceptions started to appear. The data stoped being collected. Restarting the flow helps for a short time, but right away the exceptions start appearing again.
exception:
`Error reading 40001: TimeoutError: Timeout has occurred` 
The registers.csv added in the attachment.
environment:
NODE_RED_VERSION | v3.0.2
NODE_VERSION | 16.16.0

[registers.csv](https://github.com/andrei-tatar/node-red-contrib-nibetcp/files/10875199/registers.csv)

`[
    {
        "id": "7e1a2d8aac606fa2",
        "type": "tab",
        "label": "Flow 1",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "9f36c1c77a646026",
        "type": "nibe-register",
        "z": "7e1a2d8aac606fa2",
        "name": "Outdoor temperature (BT1)",
        "register": "40001",
        "nibe": "b6df8b39681a2d06",
        "interval": "30",
        "timeout": "5",
        "force": false,
        "x": 180,
        "y": 160,
        "wires": [
            [
                "25f64ec004f0c28a"
            ]
        ]
    },
    {
        "id": "5afa3cbfb267cad6",
        "type": "influxdb out",
        "z": "7e1a2d8aac606fa2",
        "influxdb": "82fb94e85867efb2",
        "name": "write into influxdb",
        "measurement": "",
        "precision": "",
        "retentionPolicy": "",
        "database": "nibe",
        "precisionV18FluxV20": "ms",
        "retentionPolicyV18Flux": "",
        "org": "organisation",
        "bucket": "bucket",
        "x": 1070,
        "y": 640,
        "wires": []
    },
    {
        "id": "2df69ff6708bc559",
        "type": "change",
        "z": "7e1a2d8aac606fa2",
        "name": "slim down the data",
        "rules": [
            {
                "t": "delete",
                "p": "payload.raw",
                "pt": "msg"
            },
            {
                "t": "delete",
                "p": "payload.label",
                "pt": "msg"
            },
            {
                "t": "delete",
                "p": "payload.address",
                "pt": "msg"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 830,
        "y": 640,
        "wires": [
            [
                "5afa3cbfb267cad6"
            ]
        ]
    },
    {
        "id": "25f64ec004f0c28a",
        "type": "function",
        "z": "7e1a2d8aac606fa2",
        "name": "set measurement",
        "func": "measurement = msg.payload.label;\nmeasurement = measurement.replace(/\\s/g, '_').replace(/\\(/g, '').replace(/\\)/g, '');\n\nmsg.measurement = measurement.toLowerCase();\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 590,
        "y": 640,
        "wires": [
            [
                "2df69ff6708bc559"
            ]
        ]
    },
    {
        "id": "616c23f45908fa75",
        "type": "nibe-register",
        "z": "7e1a2d8aac606fa2",
        "name": "Supply Line Temperature (BT2)",
        "register": "40005",
        "nibe": "b6df8b39681a2d06",
        "interval": "60",
        "timeout": "5",
        "force": false,
        "x": 190,
        "y": 280,
        "wires": [
            [
                "25f64ec004f0c28a"
            ]
        ]
    },
    {
        "id": "f12c1901be56eec0",
        "type": "nibe-register",
        "z": "7e1a2d8aac606fa2",
        "name": "Power Usage",
        "register": "42166",
        "nibe": "b6df8b39681a2d06",
        "interval": "60",
        "timeout": "5",
        "force": false,
        "x": 140,
        "y": 400,
        "wires": [
            [
                "25f64ec004f0c28a"
            ]
        ]
    },
    {
        "id": "d079f6fe9ba1361d",
        "type": "nibe-register",
        "z": "7e1a2d8aac606fa2",
        "name": "Average Outdoor Temperature",
        "register": "40037",
        "nibe": "b6df8b39681a2d06",
        "interval": "30",
        "timeout": "5",
        "force": false,
        "x": 190,
        "y": 220,
        "wires": [
            [
                "25f64ec004f0c28a"
            ]
        ]
    },
    {
        "id": "58ccd151f314cd55",
        "type": "nibe-register",
        "z": "7e1a2d8aac606fa2",
        "name": "Degree Minutes Heating",
        "register": "30011",
        "nibe": "b6df8b39681a2d06",
        "interval": "60",
        "timeout": "5",
        "force": false,
        "x": 170,
        "y": 520,
        "wires": [
            [
                "25f64ec004f0c28a"
            ]
        ]
    },
    {
        "id": "8e9a3aee44e15b2e",
        "type": "nibe-register",
        "z": "7e1a2d8aac606fa2",
        "name": "Room Temperature (BT50)",
        "register": "40116",
        "nibe": "b6df8b39681a2d06",
        "interval": "30",
        "timeout": "5",
        "force": false,
        "x": 180,
        "y": 640,
        "wires": [
            [
                "25f64ec004f0c28a"
            ]
        ]
    },
    {
        "id": "67e805af36e550c0",
        "type": "nibe-register",
        "z": "7e1a2d8aac606fa2",
        "name": "Calculated Supply Heating",
        "register": "41017",
        "nibe": "b6df8b39681a2d06",
        "interval": "60",
        "timeout": "5",
        "force": false,
        "x": 180,
        "y": 700,
        "wires": [
            [
                "25f64ec004f0c28a"
            ]
        ]
    },
    {
        "id": "3f3aaa035ed7f1b2",
        "type": "nibe-register",
        "z": "7e1a2d8aac606fa2",
        "name": "Return Line Temperature (BT3)",
        "register": "40007",
        "nibe": "b6df8b39681a2d06",
        "interval": "60",
        "timeout": "5",
        "force": false,
        "x": 190,
        "y": 340,
        "wires": [
            [
                "25f64ec004f0c28a"
            ]
        ]
    },
    {
        "id": "b6df8b39681a2d06",
        "type": "nibe-config",
        "name": "nibe config",
        "address": "tcp://<ip-address>:502",
        "registerFile": "/data/registers.csv"
    },
    {
        "id": "82fb94e85867efb2",
        "type": "influxdb",
        "hostname": "<ip-address>",
        "port": "8086",
        "protocol": "http",
        "database": "nibe",
        "name": "InfluxDB/nibe",
        "usetls": false,
        "tls": "b56a2f8c.4744d",
        "influxdbVersion": "1.x",
        "url": "http://<ip-address>:8086",
        "rejectUnauthorized": true,
        "credentials": {}
    },
    {
        "id": "b56a2f8c.4744d",
        "type": "tls-config",
        "name": "local-tls",
        "cert": "",
        "key": "",
        "ca": "",
        "certname": "",
        "keyname": "",
        "caname": "",
        "verifyservercert": false
    }
]`

**Comment by andrei-tatar** [comment]
> I created a flow to collect data from a S1155 heat pump. I only added a few nodes, but after a short period of time exceptions started to appear. The data stoped being collected. Restarting the flow helps for a short time, but right away the exceptions start appearing again.

So I understand that it's working fine for an amount of time. Do you have a stable network connection to your heatpump? Does it recover after some time?

**Comment by pklopotowski** [comment]
yes, it works fine for a while. The connection is stable, the heat pump is directly connected to the network via Ethernet.
To give you a complete picture, Home Assistant is also connected to the same heat pump and get data without any problems. I use Home Assistant to preview current state of the pump and I want to use Node Red to collect historical data.
And regarding connection recovery => no, the connection is not restored.

**Comment by andrei-tatar** [comment]
I also had a look at my system. It seems mDNS is not working anymore, since the latest NIBE firmware update and the nodes weren't even showing the error. Will update the logic a bit

**Comment by andrei-tatar** [comment]
@pklopotowski I pushed an update. Let me know if it works better now.

**Comment by pklopotowski** [comment]
where did you publish the release? Is there any change to update here:
https://flows.nodered.org/node/@andrei-tatar/node-red-contrib-nibetcp

**Comment by andrei-tatar** [comment]
Ah, of course I always forget to update that. Done now.

**Comment by pklopotowski** [comment]
thx, update applied, will back to you with the results

**Comment by pklopotowski** [comment]
no errors, thx a lot.
