### ISSUE TITLE
Issue in connecting heatpump via modbus tcp

### ISSUE THREAD

**Issue by eminrg** [andrei-tatar/node-red-contrib-nibetcp#2]
Hi Andrei , I am trying to connect my Nibe heatpump via this plugin. and it does not work. modbus tcp is activate in the heatpump, I am running my node-red instance from a raspberry pi connected in the same lan with the heatpump. I've got ping from rpi to the heatpump. the plug in shows either disconnected or in standby. What should i look for to debug this ? Thank you

**Comment by andrei-tatar** [comment]
Hi @eminrg,
Anything relevant in the node-red logs? It should log any errors.
Is the IP address correct? Can node-red ping that IP address?
What Nibe model are you using?

**Comment by eminrg** [comment]
so something weird happened, i've put in the ping node to ping the ip of the heatpump and now it seems that it connected. Nibe heatpump used is VVMs320. One more thing , how should i use the registers.csv? according to my pumps documentation register for hot water top (bt7) is 8. but wehn i map that into the registers csv and try to read it i get this [warn] [nibe-register:909a053a4f37c5db] Error reading Hot water top (BT7): Error: Could not find register 'Hot water top (BT7)'

**Comment by andrei-tatar** [comment]
@eminrg Well, good it's working now. 
You need to enter the path to your own CSV file in the configuration node.
The CSV file I use was exported from my heat pump.

**Comment by eminrg** [comment]
when you say export from your heat pump is there a way to do that from nibe heatpump ? I just manually added the register to your example registers.csv file 
[reg.csv](https://github.com/andrei-tatar/node-red-contrib-nibetcp/files/15145509/reg.csv) and this is the message i receive
4/29/2024, 8:48:10 AM[node: d9b83c081d677336](http://192.168.1.140:1880/#)
msg : string[87]
"Error reading Hot water top (BT7): Error: Could not find register 'Hot water top (BT7)'"

**Comment by eminrg** [comment]
Found how to export the csv with registers from my pump, it works briliant now. Thank you for you work, I owe you a beer (or more)
